### ISSUE TITLE
Crash game after death

### ISSUE THREAD

**Issue by Boostem** [werty1124/SofterHardcore#1]
I installed it this morning and upon creating a hardcore world, and jumping off a cliff, i was given the option to delete world or title screen. In title screen options there was respawn, clicking it said "You're dead man, game over" and crashed my game. 

I know its installed, i got a strength buff for a few  seconds when i spawned in however.

Did i not start it correctly? Or is there another option to spawn the game with?

**Comment by werty1124** [comment]
Don't actually choose hardcore as the game mode pick survival.

**Comment by boostem** [comment]
Thank you, sorry about that

On Sunday, December 20, 2015, Dylan Greer notifications@github.com wrote:

> Don't actually choose hardcore as the game mode pick survival.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/werty1124/HardcoreExpanded/issues/1#issuecomment-166128031
> .

##
